trees:
  #   start points WGS83
  #   Justynów
  #  startPointLongitude: 19.685000
  #  startPointLatitude: 51.728355
  #  endPointLongitude: 19.685054
  #  endPointLatitude: 51.728293
  #  startEndAlt: 275.0


  startPointLongitude: 16.232411
  startPointLatitude: 52.2393905
  endPointLongitude: 16.2307455
  endPointLatitude: 52.2396365
  startEndAlt: 154.0

  #   Malownicza
#  startPointLongitude: 19.604477
#  startPointLatitude: 51.751914
#  endPointLongitude: 19.604876
#  endPointLatitude: 51.751656
#  startEndAlt: 227.0
  #
  #   altitudes
  dropBallAlt: 5.0    # [m]
  lowFlyAlt: 10.0     # [m]
  flyAlt: 30.0        # [m]
  #
  #  conversions
  #  aslToWGS83: -33.5  # Łódź
  aslToWGS83: -37.0  # Kąkolewo
  #  aslToWGS83: -10.0   # Simulation Gazebo
  #
  #   Accuracy
  dropWaypointAccuracy: 0.5       # [m]
  waypointPositionAccuracy: 0.8   # [m]
